### PR TITLE
Document default branch behaviour

### PR DESCRIPTION
**Pull request by murrayju**
Document the behavior of renaming the default branch to master, and how to override when this causes problems. See #182.

### CODE REVIEW

**Comment by frej** [comment]
I like the patch, but please shorten the subject to be less than 80 characters, [this recommends 50 characters, but I myself break that from time to time](https://chris.beams.io/posts/git-commit/l)

**Comment by murrayju** [comment]
@frej I assume you are referring to the git commit message, but the first line of my commit (what I think you are calling the "subject") is only 16 characters.

Are you asking me to make it more descriptive, but limit that to 80 characters?

**Comment by frej** [comment]
Sorry, I got confused by just having a quick look at the commit message on github and not with git log. What I should have said was (If I wasn't in a hurry): Make the subject more descriptive and make sure to line break the rest of the message to at most 80 chars.

**Comment by frej** [comment]
Why not "Document default branch behaviour" as the subject? That it goes into the README is pretty obvious from the diffstat. The body of the commit message is not line folded to less than 80 characters.

**Comment by frej** [comment]
Looks good now, thank you for your contribution!

**Pull request merged**
