### PR TITLE
Resolve issue #203: Encode stderr with UTF8 on PY2

### PR DESCRIPTION
**Pull request by chrisjbillington**
In Python 3, `sys.stderr.write()` requires unicode strings, and all
output on standard streams is UTF8 encoded. Therefore in the port to
Python 3, we `.decode()`d all strings that are used in `%` formatting of
strings to be printed to stderr.

However, in Python 2, `sys.stderr` accepts either bytestrings or unicode
strings, and:

- `%s` formatting of a bytestring with a unicode string, i.e  `"%s" %
  u"foo"` results in a unicode string.
- Writing a unicode string to stderr/stdout uses that stream's encoding
- When the output of the process is being piped somewhere other than a
  terminal (as it is when called with pipes and shell redirection from
  hg-fast-export.sh), that encoding is None, which implies ASCII.
- This raises UnicodeEncodeError if the unicode strings passed to
  `stderr.write()` have non-ascii characters.

Therefore we should not write unicode strings to stderr in Python 2. All
strings should be encoded UTF8 first.

This commit does that by using `codecs.getwriter("utf8")(sys.stderr)` as
the file-like object to write to instead of `sys.stderr` directly. This
brings the behaviour of writing to stderr on Python 2 in line with that
of Python 3.

The outputting to stderr in hg2git.py and
`shell_filter_file_contents/__init__.py` only use "native" strings and
so do not need to be modified to work correctly on both Python versions.

### CODE REVIEW

**Comment by EraYaN** [comment]
This appears to fix the issue even if the reported encoding of stderr is `None` (when running as a child from a `subprocess.run` call.

**Comment by chrisjbillington** [comment]
I'm actually not quite happy with this.

UTF8 is not quite ok, since filenames can actually be invalid UTF8 on unix. We would need to use the `surrogateescape` error handler on Py3 so that UTF8-invalid filepaths round-trip, and just not decode on Python2 (where that error handler doesn't exist).

I'll figure it out!

**Comment by chrisjbillington** [comment]
Ok, I've resolved my further concerns about filenames potentially not even being valid UTF8.

@EraYaN could you test again?

New commit message below:

----

In Python 3, `sys.stderr.write()` requires unicode strings, and all
output on standard streams is UTF8 encoded. Therefore in the port to
Python 3, we `.decode()`d all strings that are used in `%` formatting of
strings to be printed to stderr.

However, in Python 2, `sys.stderr` accepts either bytestrings or unicode
strings, and:

- `%s` formatting of a bytestring with a unicode string, i.e  `"%s" %
  u"foo"` results in a unicode string.
- Writing a unicode string to stderr/stdout uses that stream's encoding
- When the output of the process is being piped somewhere other than a
  terminal (as it is when called with pipes and shell redirection from
  hg-fast-export.sh), that encoding is None, which implies ASCII.
- This raises UnicodeEncodeError if the unicode strings passed to
  `stderr.write()` have non-ascii characters.

We cannot fix this problem simply by encoding UTF8 again before writing
to stderr on Python 2. This is because the *decoding* of filenames with
the UTF8 codec may fail - filenames may not even be valid UTF8 desite
this being the declared filesystem encoding.

We could `fsdecode()` filenames on Python 3, which would use the
`surrogateescape` error handler, but stderr does not use this error
handler for output, meaning we would just have to encode again (with the
same error handler) anyway. And Python 2 lacks the `surrogateescape`
error handler in any case - we would need to reimplement it just to do a
round-trip decode and encode for no reason.

This commit leaves filenames and other repository data as bytestrings,
and simply writes them to `sys.stderr.buffer` on Python 3 or
`sys.stderr` on Python 2 as-is, after `%` formatting with bytestring
literals. This avoids encoding issues of filenames altogether.

Other writing to stderr that does not involve repository data has been
left with "native" strings, i.e.
`sys.stderr.write("a string literal %s" % a_command_line_arg)`. These
will still fail on Python 3 if the user passes a non-UTF filename as a
command line argument or similar. This is acceptable IMHO - although
`hg-fast-export` may encounter invalid UTF8 in mercurial repositories,
it is not too much to impose that the user name their branch mapping
files etc with valid UTF8!

**Comment by EraYaN** [comment]
With the new changes, it still works.

**Comment by frej** [comment]
Nicely done @chrisjbillington, I greatly appreciate you taking responsibility for, and fixing issues discovered in your previous work. Thank you for your contribution!

**Comment by chrisjbillington** [comment]
You're welcome @frej! Thanks for merging.

**Pull request merged**
