### PR TITLE
Additional validation for branch names.

### PR DESCRIPTION
**Pull request by daolis**
Must match regex '^[^a-zA-Z0-9\/\.\(\)_-]*([a-zA-Z0-9\/\.\(\)_-]*)' to avoid getting branch names with special characters

Someways it happens that developers created branch names that contains speacial characters. Convertion for this branches fails, so i added this check. (Branch Names will be changed)

### CODE REVIEW

**Comment by juRiii** [comment]
@daolis will you do something here?

**Comment by austinforlife** [comment]
@daolis pretty please?

**Comment by frej** [comment]
3c27c693e13482059966003dd6545941b942a97a should allow you to fix up branch names

**Comment by frej** [comment]
Seems to be resolved by 3c27c693e13482059966003dd6545941b942a97a, closing.

**Pull request closed without merging**
