### PR TITLE
fix for crash specified in issue 207

### PR DESCRIPTION
**Pull request by madmaxreach**
Fixing crash with a type error.

### CODE REVIEW

**Comment by frej** [comment]
@madmaxreach : Please include the reason for the change in the commit message (please see [How to Write a Git Commit Message](https://chris.beams.io/posts/git-commit/) for what constitutes a good commit message) instead of just referring to the issue number.

@chrisjbillington: You're my Python 3 expert, as far as I can tell this will work both for Python 2 and 3, correct?

**Comment by chrisjbillington** [comment]
@frej yes, this looks like the correct fix to me.

Issue #207 is Python 3 specific, Python 2 doesn't mind if you give an int to `b'%s'`, but Python 3 refuses to automatically convert. Both are happy with `b'%d' % an_integer`.

**Comment by madmaxreach** [comment]
@frej commit message should now be useful, let me know if you'd like it updated!

**Comment by frej** [comment]
> @frej commit message should now be useful, let me know if you'd like it updated!

Much better, thank you for your contribution.

@chrisjbillington: Thanks for the sanity check.

**Pull request merged**
