### PR TITLE
Suggested changes to add plugin support for the 'extra' field

### PR DESCRIPTION
**Pull request by SirIntellegence**
Seems to work in my copy, but I am not a python programmer, so you may want to double check it?

### CODE REVIEW

**Comment by SirIntellegence** [comment]
See #257

**Review by frej — CHANGES_REQUESTED** [review]
Oh, it was that simple!

Please amend your commit to update the **Plugins** section in `README.md` to document the change, also take a look at the **Submitting Patches** section and make sure that your commit message follows Chris Beams' suggestions.

**Review by frej — CHANGES_REQUESTED** [review]
Why not just change the commit subject to "Add plugin support for the 'extra' field"? We are way past suggestions now, this is a patch I want to merge! I could make the edit, but as your name will be associated with the final result, I prefer not to do it, as it could be considered stepping on your toes.

**Comment by SirIntellegence** [comment]
Ah, didn't think about that. Just a moment...

**Comment by SirIntellegence** [comment]
Also, for reference, I currently can only confirm that it doesn't crash. I haven't tried reading "extra" yet.

**Comment by SirIntellegence** [comment]
I just recently tested it and it does work properly

**Comment by frej** [comment]
Merged, thank you for your contribution.

**Review by frej — APPROVED** [review]

**Pull request merged**
