### PR TITLE
Adding doc updates

### PR DESCRIPTION
**Pull request by admiralAwkbar**
- update docs
- add `Dockerfile`

@frej  love the work you have on this. Was using it and wanted to help contribute back!

Will eventually add back to the bash and python code once tested a bit more :)

The `Dockerfile` was a nice way to help users distribute this and have a repeatable env

### CODE REVIEW

**Review by frej — CHANGES_REQUESTED** [review]
> @frej love the work you have on this. Was using it and wanted to help contribute back!

Thanks, I guess this means I should close #267 as resolved?

Please read the "Submitting Patches" section in the README and revise this PR. From the commit message I would expect this patch to do something with the documentation, that it does, but after a quick look I find that it also adds docker files and changes the workflow setup. When good commit hygiene is applied I would expect to see three commits, one for each logical change.

From my quick look, I see that you in some places tag the contents of ordinary text files as bash, why?

I'm not likely to accept the Docker parts. I don't use Docker and therefore I won't accept something that I know will bit-rot over time.

Submitting changes to the workflow setup without mentioning it in the commit message will probably make most maintainers deeply suspicious. Is the potential contributor trying to slip in something nasty?

**Comment by admiralAwkbar** [comment]
@frej 
Hey thanks for the feedback.

Yeah if your not keen on `Docker` then I would say to remove it. It was helpful to get an exporter instance up and running with the code base and helps users have a repeatable env that you can test, develop, and repeat.

I forgot I had the `Super-Linter` for my local testing and it was a big push.
Its a great tool to help solve coding practices, and ill remove as that shouldn't have came with my push.

The coding brackets should have been text and will update

**Comment by frej** [comment]
Making a stone statue out of a block of stone is simple, you just chisel away all material which does not belong to the finished statue. Although this is admired in stonemasonry, it is not the way to make a software maintainer happy :)

Please make sure your pull-request follows the advice given in the ["Submitting Patches"](https://github.com/frej/fast-export#submitting-patches)  section in the README. Apart from being very hard to review in its current state, there is no point in maintaining the PR revision history.

**Comment by admiralAwkbar** [comment]
@frej its fine ill close this

**Pull request closed without merging**
