### PR TITLE
Show warning when core.ignoreCase is true

### PR DESCRIPTION
**Pull request by emilianbold**
As discussed on https://github.com/frej/fast-export/issues/87

### CODE REVIEW

**Comment by frej** [comment]
Technically this looks good to me, but please flesh out the commit message so the motivation for this feature is clear without having to check the github issue tracker. See, for example, https://who-t.blogspot.se/2009/12/on-commit-messages.html for inspiration. Also fix the typo on the summary line, it should read  "Show warning...".

**Comment by emilianbold** [comment]
Done.

Happy New Year!

**Comment by frej** [comment]
> Done.

I fleshed out the commit message further, and did some massaging of the
error message to fit into 80 cols. Thank you for your contribution.


> Happy New Year!

And the same to you!

**Comment by frej** [comment]
Patch merged

**Pull request closed without merging**
